# Generates chatwoot-local/.env with random secrets if missing.
# Usage: powershell -ExecutionPolicy Bypass -File .\new-env.ps1
$ErrorActionPreference = 'Stop'
$dir = Split-Path -Parent $MyInvocation.MyCommand.Path
$envFile = Join-Path $dir '.env'
if (Test-Path $envFile) {
    Write-Host ".env already exists at $envFile . Remove it first if you want to regenerate."
    exit 0
}
$hex = { param($n) -join ((1..$n) | ForEach-Object { '{0:x}' -f (Get-Random -Max 16) }) }
$secret = & $hex 64
$lockbox = & $hex 64
$pgpass = & $hex 24
$content = @(
    '# Chatwoot local dev environment (generated by new-env.ps1)',
    'POSTGRES_HOST=postgres',
    'POSTGRES_USERNAME=postgres',
    "POSTGRES_PASSWORD=$pgpass",
    'POSTGRES_DATABASE=chatwoot_production',
    'REDIS_URL=redis://redis:6379',
    "SECRET_KEY_BASE=$secret",
    "LOCKBOX_MASTER_KEY=$lockbox",
    'FRONTEND_URL=http://localhost:3000',
    'DEFAULT_LOCALE=zh_CN',
    'RAILS_ENV=production',
    'RAILS_LOG_TO_STDOUT=true',
    'LOG_LEVEL=info',
    'ENABLE_ACCOUNT_SIGNUP=true',
    'ACTIVE_STORAGE_SERVICE=local',
    'SIDEKIQ_CONCURRENCY=5'
)
$content | Set-Content -Path $envFile -Encoding ASCII
Write-Host ".env created: $envFile"
